version: '3'

services:
  frontend-app:
    working_dir: /app
    container_name: frontend-app
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development

    ports:
      - "3000:3000"

    volumes:
      - ./:/app:ro
    environment:
      PORT: 3000
      NODE_ENV: development