export const GET_LIST_PRODUCT_ACTION = 'app/ProductPage/GET_LIST_PRODUCT_ACTION';
export const GET_LIST_PRODUCT_SUCCESS = 'app/ProductPage/GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_FAILED = 'app/ProductPage/GET_LIST_PRODUCT_FAILED';
