name: react-template

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test-lints:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [14.x, 18.x]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Check lint
        run: npm run lint

      - name: Build
        run: npm run build
    
